name: my_flutter_app
description: A Flutter project for file auditing system.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  path: ^1.8.3
  intl: ^0.18.0
  csv: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.14
  file_manager: ^1.0.0
  path_provider: ^2.1.1
  flutter_treeview: ^1.0.7
  shared_preferences: ^2.2.1
  permission_handler: ^11.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  logger: ^1.4.0
  flutter_markdown: ^0.6.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/  # 폰트 파일 경로
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900